### ISSUE TITLE
Internal server error caused by permission denied error

### ISSUE THREAD

**Issue by macvfx** [munki/mwa2#13]
User gets an "Internal server error" when MWA encounters a permission denied error. Trying to duplicate some manifests gave me this error. I guess permissions, and this was confirmed by the output in Terminal:

```
Got create request for test
Internal Server Error: /manifests/test
Traceback (most recent call last):
  File "/Users/ladmin/Downloads/mwa2_demo/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ladmin/Downloads/mwa2_demo/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ladmin/Downloads/mwa2_demo/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/ladmin/Downloads/mwa2_demo/mwa2/manifests/views.py", line 102, in detail
    request.user)
  File "/Users/ladmin/Downloads/mwa2_demo/mwa2/manifests/models.py", line 182, in write
    raise ManifestWriteError(err)
ManifestWriteError: [Errno 13] Permission denied: u'/Users/Shared/munki_repo_test/manifests/test'
```

**Comment by gregneagle** [comment]
Cosmetic improvements to the error alerts/modals welcome.
